version: 2.1
orbs:
  tfsec: mycodeself/tfsec@1.1.0
  go: circleci/go@1.7.3
jobs:
  pre-test:
    resource_class: ewsaxyfkcp5g9tbybh5unx/test
    executor: tfsec/default
    steps:
      - checkout
      - tfsec/scan:
          directory: ./infrastructure
          exclude-checks: 'aws-ec2-require-vpc-flow-logs-for-all-vpcs,aws-ec2-enable-at-rest-encryption,aws-ec2-enforce-http-token-imds,aws-ec2-no-public-egress-sgr,aws-ec2-no-public-ingress-sgr,aws-ec2-add-description-to-security-group-rule'
  post-test:
    resource_class: ewsaxyfkcp5g9tbybh5unx/test
    executor:
      name: go/default
      tag: '1.19.2'
    steps:
      - checkout
      - run: wget https://releases.hashicorp.com/terraform/1.8.3/terraform_1.8.3_linux_amd64.zip
      - run: sudo unzip terraform_1.8.3_linux_amd64.zip -d /usr/local/bin
      - run: wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.58.5/terragrunt_linux_amd64
      - run: cp terragrunt_linux_amd64 terragrunt
      - run: chmod u+x terragrunt
      - run: sudo mv terragrunt /usr/local/bin/terragrunt

      - run:
          name: terratest
          command: |
            cd terratest/test \
              && go mod init terraformtest \
              && go mod tidy \
              && go test -v


workflows:
  version: 2
  test-deployment:
    jobs:
      - pre-test
      - post-test
