apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tf-app
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/phosphor-v/webserver-ec2-module-terraform
  ref:
    branch: ${CIRCLE_BRANCH}
  secretRef:
    name: flux-system
