apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tf-app
  namespace: flux-system
spec:
  vars:
  - name: env
    value: ${CIRCLE_BRANCH}
  backendConfig:
    customConfiguration: |
      backend "s3" {
        bucket                      = "phosphor-tfstates"
        key                         = "${CIRCLE_BRANCH}/terraform.tfstate"
        region                      = "us-east-1"
      }
  backendConfigsFrom:
    - kind: Secret
      name: terraform-s3-backend
      keys:
        - access_key
        - secret_key
      optional: false
  interval: 1m0s
  path: ./infrastructure
  sourceRef:
    kind: GitRepository
    name: tf-app
  approvePlan: auto
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: aws-credentials